refresh_rate: 30 seconds
appenders:
  stdout:
    kind: console
    encoder:
      pattern: "[{h({l})}] {d(%Y-%m-%d %H:%M:%S %Z)} | {m} | {M}/{f}{n}"
  daemon:
    kind: file
    path: "log/daemon.log"
    encoder:
      pattern: "[{h({l})}] {d(%Y-%m-%d %H:%M:%S %Z)} | {m} | {M}/{f}{n}"
root:
  level: info
  appenders:
    - daemon
    - stdout
